version: '3.8'

services:
  redis1:
    image: bitnami/redis:latest
    container_name: redis-server-1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:  
      - "6379:6379"

  grpcserver:
    build: .
    container_name: grpc-server
    environment:
      - REDIS_HOST=redis1  # Variable de entorno para Redis
      - GRPC_PORT=50051    # Variable de entorno para el puerto gRPC
    ports:
      - "50051:50051"
    depends_on:
      - redis1

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis1
