# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dns_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dns_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ns_service.proto\x12\x0b\x64ns_service\"\x1c\n\nDNSRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"!\n\x0b\x44NSResponse\x12\x12\n\nip_address\x18\x01 \x01(\t2O\n\x08\x44NSCache\x12\x43\n\x0eGetDNSResponse\x12\x17.dns_service.DNSRequest\x1a\x18.dns_service.DNSResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dns_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DNSREQUEST']._serialized_start=34
  _globals['_DNSREQUEST']._serialized_end=62
  _globals['_DNSRESPONSE']._serialized_start=64
  _globals['_DNSRESPONSE']._serialized_end=97
  _globals['_DNSCACHE']._serialized_start=99
  _globals['_DNSCACHE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
